// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBShwAbMT9RdA15UAlMlY3g0dD9WvpKHvg',
    appId: '1:622781979030:android:d808eb91b7dfdfcbd925b7',
    messagingSenderId: '622781979030',
    projectId: 'gymapp-ed1bd',
    storageBucket: 'gymapp-ed1bd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-C-ApGlIjWprvsrj-HvqN3ofvz88sPo',
    appId: '1:622781979030:web:b56a965a76f8e2add925b7',
    messagingSenderId: '622781979030',
    projectId: 'gymapp-ed1bd',
    authDomain: 'gymapp-ed1bd.firebaseapp.com',
    storageBucket: 'gymapp-ed1bd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7GPWCp04dvryH2Dio2-IdiFVHAgvui5I',
    appId: '1:622781979030:ios:9856d1c7ba7be126d925b7',
    messagingSenderId: '622781979030',
    projectId: 'gymapp-ed1bd',
    storageBucket: 'gymapp-ed1bd.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiGym',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7GPWCp04dvryH2Dio2-IdiFVHAgvui5I',
    appId: '1:622781979030:ios:9856d1c7ba7be126d925b7',
    messagingSenderId: '622781979030',
    projectId: 'gymapp-ed1bd',
    storageBucket: 'gymapp-ed1bd.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB-C-ApGlIjWprvsrj-HvqN3ofvz88sPo',
    appId: '1:622781979030:web:3d8aba6116759f44d925b7',
    messagingSenderId: '622781979030',
    projectId: 'gymapp-ed1bd',
    authDomain: 'gymapp-ed1bd.firebaseapp.com',
    storageBucket: 'gymapp-ed1bd.firebasestorage.app',
  );

}